name: CI

on:
  push:
    branches: hw2

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: sh ./script_install.sh
      - name: test cppcheck
        run: cppcheck main.c lib_consistent/*.c lib_parallel/*.c lib_manage_data/*.c --enable=all --inconclusive -I include --suppress=missingIncludeSystem
      - name: test clang-tidy
        run: clang-tidy main.c lib_consistent/*.c lib_parallel/*.c lib_manage_data/*.c -warnings-as-errors=* -extra-arg=-std=c99 -- -Iinclude
      - name: test cpplint
        run: cpplint --extensions=c main.c lib_consistent/*.c lib_parallel/*.c lib_manage_data/*.c 
      - name: test scan-build
        run: scan-build gcc main.c lib_consistent/*.c lib_parallel/*.c lib_manage_data/*.c -Iinclude
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: sh ./script_install.sh
      - name: build main
        run: |
         mkdir build
         cd build
         cmake ..
         make     
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: sh ./script_install.sh
      - name: gtests
        run: |
         mkdir build
         cd build
         cmake ..
         make
         ./tests
      - name: report lcov
        run: |
          cd build
          lcov -t "tests" -o coverage_parallel.info -c -d CMakeFiles/FIND_PARALLEL_LIB.dir/
          lcov -t "tests" -o coverage_consistent.info -c -d CMakeFiles/FIND_CONSISTENT_LIB.dir/
      - name: result coverage tests
        run: |
          genhtml -o report_parallel coverage_parallel.info
          genhtml -o report_consistent coverage_consistent.info


      
      
