name: CI

on:
  push:
    branches: hw2

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: sh ./script_install.sh
      - name: test cppcheck
        run: cppcheck main.c lib_consistent/*.c lib_parallel/*.c lib_manage_data/*.c --enable=all --inconclusive -I include --suppress=missingIncludeSystem
      - name: test clang-tidy
        run: clang-tidy main.c lib_consistent/*.c lib_parallel/*.c lib_manage_data/*.c -warnings-as-errors=* -extra-arg=-std=c99 -- -Iinclude
      - name: test scan-build
        run: scan-build gcc main.c lib_consistent/*.c lib_parallel/*.c lib_manage_data/*.c -Iinclude -pthread
  build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: sh ./script_install.sh
      - name: build main
        run: |
         mkdir build
         cd build
         cmake ..
         make     
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: sh ./script_install.sh
      - name: gtests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./tests
      - name: report lcov
        run: |
          cd build
          lcov -t "tests" -o coverage_parallel.info -c -d CMakeFiles/FIND_PARALLEL_LIB.dir/
          lcov -t "tests" -o coverage_consistent.info -c -d CMakeFiles/FIND_CONSISTENT_LIB.dir/
          lcov -t "tests" -o coverage_manage_data.info -c -d CMakeFiles/FIND_MANAGE_DATA_LIB.dir/
      - name: result coverage tests
        run: |
          cd build
          genhtml -o report_parallel coverage_parallel.info
          genhtml -o report_consistent coverage_consistent.info
          genhtml -o report_manage_data coverage_manage_data.info
      - name: run main
        run: |
          cd build
          ./hw2
      - name: test valgrind
        run: |
          cd build
          valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./hw2


      
      
