name: CI

on:
  push:
    branches: hw1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: sh ./script_install.sh
      - name: build main
        run: |
         mkdir build
         cd build
         cmake ..
         make
      - run: ls -la
      - name: upload artifacts
        uses: actions/upload-artifact@v2 
        with:
          path: /main.out
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: sh ./script_install.sh
      - run: |
         mkdir build
         cd build
         cmake ..
         make
         ./tests/test_countries
      
      
